"""Add date column to memos

Revision ID: 094c5a6ae500
Revises: 080fc37e9000
Create Date: 2026-02-28 14:22:33.895902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094c5a6ae500'
down_revision = '080fc37e9000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
