"""add autofiller

Revision ID: 225885d67ab2
Revises: 566955ebb586
Create Date: 2026-04-11 19:19:11.647440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225885d67ab2'
down_revision = '566955ebb586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memo_autocomplete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memo_autocomplete')
    # ### end Alembic commands ###
