"""empty message

Revision ID: 2df668194e77
Revises: 7089fc74ea2a
Create Date: 2026-03-26 02:22:05.049068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df668194e77'
down_revision = '7089fc74ea2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_log_entries')
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_log_entries_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_log_entries_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('_alembic_tmp_log_entries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('serial_number', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=255), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('encoded_at', sa.DATETIME(), nullable=True),
    sa.Column('memo_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['memo_id'], ['memos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_log_entries_user_id')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    # ### end Alembic commands ###
