"""add thread_id

Revision ID: 566955ebb586
Revises: 2df668194e77
Create Date: 2026-04-09 21:20:32.808383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566955ebb586'
down_revision = '2df668194e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_id', sa.String(length=50), nullable=False))

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.drop_column('thread_id')

    # ### end Alembic commands ###
